name: Report an issue
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        This template is used for reporting an issue with better-blog.

        Feature requests should be opened in [here](https://github.com/olliethedev/better-blog/issues/new?assignees=&labels=&projects=&template=feature_request.md&title=).

        Before opening a new issue, please do a [search](https://github.com/olliethedev/better-blog/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        Ex:
        1. Create a blog site
        2. Configure settings
        3. X will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: |
        A clear and concise description of what the bug is (e.g., screenshots, logs, etc.), and what you expected to happen.

        **Skipping this/failure to provide complete information of the bug will result in the issue being closed.**
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead.'
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Better Blog are you using?
      description: Please provide the current version of `better-blog` that you are reporting the bug on
      placeholder: "1.x.x"
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info
      description: Output of `npx envinfo --system --browsers`
      render: bash
      placeholder: System and browsers
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Backend'
        - 'Client'
        - 'Types'
        - 'Documentation'
        - 'Package'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate. For example, is it only reproducible online, or locally too? Is the issue only happening in a specific browser? etc.
      placeholder: |
        I tested my reproduction against the latest release.