name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
      DOCKER_BUILDKIT: 1
    services:
      # Docker daemon is available by default on ubuntu-latest
      # No explicit Postgres service; we use Testcontainers per-project
      # and spawn isolated containers.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm e2e:install

      - name: Build workspace
        run: pnpm -w build

      - name: Run Playwright tests
        run: pnpm e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/*.zip
          if-no-files-found: ignore


